services:
  backend:
    build: ./backend
    image: chat-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend 
    image: chat-frontend
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_API_BASE_URL=http://3.80.232.124:5000/
    depends_on:
      - backend
